### ISSUE TITLE
Приложение не находит драйвер для работы с PostgreSQL

### ISSUE THREAD

**Issue by nicklada** [nicklada/Final#15]
#Приложение не находит драйвер для работы с PostgreSQL 

## Шаги воспроизведения ##
1. Скачайте в локальный репозиторий все файлы с данного репозитория (можно воспользоваться командой `git pull`)
2. Создайте контейнер Docker для работы с БД командой `docker-compose up`
3. Запустите работу базы postgeSQL в контейнере командой `docker exec -it app_db psql -U app -W app app`
В открывшееся поле ввода пароля введите пароль: `pass`
4. Запустите работу приложения командой `java -jar aqa-shop.jar`
5. Запустите симулятор банковских серверов (для имитации ответа на запросы) командой` npm start`
6. Запустите тестовые методы командой  `./gradlew clean test`

## Ожидаемый результат #
Тестовые методы стартуют и выполняются

## Полученный результат ##
Тестовые методы не запускаются по причине отсутствия драйвера для работы с PostgreSQL

![Снимок экрана 2020-08-18 в 17 41 44](https://user-images.githubusercontent.com/61970788/90527439-37ffeb80-e17a-11ea-949d-ea06af709cb5.png)

## Log ##
```
No suitable driver found for jdbc:postgresql://localhost:5432/app
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/app
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at ru.netology.web.data.TablesHelper.cleanData(TablesHelper.java:18)
	at ru.netology.web.test.FormCreditTest.cleanTablesBefore(FormCreditTest.java:21)

```
## Окружение ##
OS Version: Mac OS High Sierra
Java version: Openjdk version "11.0.6" 2020-01-14
Link to the project on [ GitHub ](https://github.com/nicklada/HW8Task2)

**Comment by nicklada** [comment]
не является дефектом
отсутствовал драйвер
